#!/usr/bin/env python3
# Copyright (c) 2026 Scott Armstrong and Vlad Vicol.
# Released under Apache 2.0 license.
"""Build every tracked CKN module, including examples and auxiliary results."""
import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
argparse.ArgumentParser(description=__doc__).parse_args()
tracked = subprocess.check_output(["git", "ls-files", "-z", "CKN"], cwd=ROOT).decode().split("\0")
modules = sorted(p[:-5].replace("/", ".") for p in tracked if p.endswith(".lean"))
if not modules:
    raise SystemExit("build_all: no tracked CKN modules found")
(ROOT / "CKNAll.lean").write_text(
    "-- Generated by scripts/build_all.py.\n"
    + "".join(f"import {module}\n" for module in modules)
)
print(f"CKNAll.lean: {len(modules)} modules", flush=True)
raise SystemExit(subprocess.call([sys.executable, str(ROOT / "scripts/build.py"), "CKNAll"], cwd=ROOT))
